### ISSUE TITLE
Avoid duplicate css class names by replacing Math.random()

### ISSUE THREAD

**Issue by B-Teague** [lukejacksonn/csz#5]
Suggest replacing Math.random() with a perfect 32bit hash function to avoid collisions which could cause duplicate css class names

## [Robert Jenkins' 32 bit integer hash function](https://gist.github.com/badboy/6267743)

```js
import stylis from './stylis.js'

const cache = {}
let seed = 0;  // or Math.random() * 4294967295;
const p = new Uint32Array(1);
const hash = () => {
  //Math.random()
  p[0] = seed++;
  p[0] = (p[0]+0x7ed55d16) + (p[0]<<12);
  p[0] = (p[0]^0xc761c23c) ^ (p[0]>>19);
  p[0] = (p[0]+0x165667b1) + (p[0]<<5);
  p[0] = (p[0]+0xd3a2646c) ^ (p[0]<<9);
  p[0] = (p[0]+0xfd7046c5) + (p[0]<<3);
  p[0] = (p[0]^0xb55a4f09) ^ (p[0]>>16);
  return p[0].toString(16);
}

const sheet = document.createElement('style')
document.head.appendChild(sheet)
```

## Sample output
> "1: b48681b6"
> "2: e267b84c"
> "3: b0910e9c"
> "4: c797201d"
> "5: fe0d66ee"
> "6: f2b32b34"
> "7: f3ced760"
> "8: 92daf2f4"
> "9: b5b9ef41"

## Math.random() vs 32bit Hash function performance
https://jsbench.me/
### Using cache with Math.random() to prevent collision
const cache = {
    abc123: true,
    def123: true,
    aba123: true,
    bab123: true,
    bcb123: true,
    cdc123: true,
    dde123: true,
}
const hash = Math.random().toString(36).replace('0.', '')
cache[hash]
844,675 ops/s ±2.41%
65.03% slower

### Using 32bit hash function
let seed = 0;  // or Math.random() * 4294967295;
const p = new Uint32Array(1);  
p[0] = seed++;
  p[0] = (p[0]+0x7ed55d16) + (p[0]<<12);
  p[0] = (p[0]^0xc761c23c) ^ (p[0]>>19);
  p[0] = (p[0]+0x165667b1) + (p[0]<<5);
  p[0] = (p[0]+0xd3a2646c) ^ (p[0]<<9);
  p[0] = (p[0]+0xfd7046c5) + (p[0]<<3);
  p[0] = (p[0]^0xb55a4f09) ^ (p[0]>>16);
  p[0].toString(16);

2,415,448 ops/s ±0.52%
fastest

**Comment by B-Teague** [comment]
Another option is just use a counter instead of generated hash names like picostyle. 
csz-1, csz-2, csz-3, etc.
This provides unique class names if the user doesn't care about class names and is more efficient than the suggested solution above.

If developers do care about class names, then a solution to issue #6 needs to be implemented

**Comment by lukejacksonn** [comment]
Random is hard 😅 the chance of collision is pretty minute here although you make a good point about replacing (or prefixing I guess) the random hash with a incrementing integer.

This kinda feels like a over optimisation as `Math.random().toString(36).replace('0.', '')` should be sufficient in most cases. If you are creating enough unique styles to start worrying about perf degradation and collisions then you have bigger things to worry about!

**Comment by B-Teague** [comment]
Yup, definitely over optimizing. I like math =)
I think for both efficiency and transparency, the best solution would be a counter and custom css class names.

```diff
import stylis from './stylis.js'

const cache = {}
+let csz = 0
-const hash = () =>
-  Math.random()
-    .toString(36)
-    .replace('0.', '')

const sheet = document.createElement('style')
document.head.appendChild(sheet)

-const none = hash => `.${hash}{display:none}`
+const none = className => `.${className}{display:none}`
-const hide = hash => (sheet.innerHTML = none(hash) + sheet.innerHTML)
+const hide = className => (sheet.innerHTML = none(className) + sheet.innerHTML)
-const show = hash => (sheet.innerHTML = sheet.innerHTML.replace(none(hash), ''))
+const show = className => (sheet.innerHTML = sheet.innerHTML.replace(none(className), ''))

-const process = key => hash => rules => {
+const process = key => className => rules => {
-  if (key.startsWith('/')) show(hash)
+  if (key.startsWith('/')) show(className)
  sheet.innerHTML += (cache[key] = {
-    hash,
+    className,
-    rules: stylis()(`.${hash}`, rules),
+    rules: stylis()(`.${className}`, rules),
  }).rules
}

export default (strings, ...values) => {
+ //csz`.my-class { background: blue; }`
+ const classPrefix= strings[0].startsWith('.') ? strings[0].substring(1, strings[0].indexOf(' ')) : "csz-"
  const key = strings[0].startsWith('/')
    ? strings[0]
    : strings.reduce(
        (acc, string, i) =>
          (acc += string + (values[i] == null ? '' : values[i])),
        ''
      )

-  if (cache[key]) return cache[key].hash
+  if (cache[key]) return cache[key].className

-  const className = 'csz-' + hash()
+  const className = (classPrefix.charAt(--classPrefix.length) === '-' ? classPrefix : classPrefix + '-') + csz++
  const append = process(key)(className)

  if (key.startsWith('/')) {
    hide(className)
    fetch(key)
      .then(res => res.text())
      .then(append)
+ } else if (key.startsWith('.')) {
+   // Below supports both csz`.my-class { background: blue; }` Or csz`.my-class background: blue;`
+   const ruleStart = key.indexOf(' ') === key.replace(' ', '').indexOf('{') ? key.indexOf('{') : key.indexOf(' ')
+   const ruleEnd = key.trim().lastIndexOf('}') === key.length - 1 ? key.lastIndexOf('}') : key.length
+   apend(key.substring(ruleStart + 1, ruleEnd))
  } else append(key)

  return className
}
```
