### ISSUE TITLE
Worth adding custom class names?

### ISSUE THREAD

**Issue by B-Teague** [lukejacksonn/csz#6]
Do you think adding custom css class name support is worth it from a debugging perspective?

Example:
.my-class-name-af28f1eb
.another-class-name-e3fd91bc
instead of
.csz-af28f1eb
.csz-e3fd91bc

I'm not sure how you would support this since your css function call uses a template string.
css('background: blue', 'my-class-name')

**Comment by lukejacksonn** [comment]
Hey man 👋 thanks for creating some issues! I'm not sure about this one, generally for debugging I resort to something like `background: hotpink;` 😅 but I know that the likes of emotion and styled-components grab the function name and incorporate it into class name in dev. Maybe this could be done in a similar way 🤔
